version: '3.8'

services:
  jupyterhub:
    build: .
    container_name: ten-jupyterhub
    networks:
      - tensor-network
    volumes:
      - .:/srv/jupyterhub/
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8800:8000"
    environment:
         - SPAWNER_IMAGE=cschranz/gpu-jupyter:v1.5_cuda-11.6_ubuntu-20.04
         - SPAWNER_NETWORK=tensor-network
         - SPAWNER_DEFAULT_URL=/lab
         - TIMEOUT=120
         - CULL-EVERY=600
         - SHARED_FOLDER=/home/sysadmin/Shared
         - LDAP-ADDRESS=
         - SEARCH-BASE=
