services:
  jupyterhub:
    build: .
    container_name: jupyterhub
    networks:
      - jupyterhub-network
    volumes:
      - .:/srv/jupyterhub/
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8000:8000"
    environment:
         - SPAWNER_IMAGE=jupyter/datascience-notebook
         - SPAWNER_NETWORK=jupyterhub-network
         - SPAWNER_DEFAULT_URL=/lab
         - TIMEOUT=120
         - CULL-EVERY=600
         - SHARED_FOLDER=./Shared
    command: ["jupyterhub", "--url=http://:8000/hub1"]

networks:
  jupyterhub-network:
    name: jupyterhub-network

